// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb_qM0YRN5iFesfOXrAPQzcYUdRzJhn0g',
    appId: '1:1064041710776:web:5cc1f2ce267e2b2cb3e04d',
    messagingSenderId: '1064041710776',
    projectId: 'carnava-15594',
    authDomain: 'carnava-15594.firebaseapp.com',
    storageBucket: 'carnava-15594.firebasestorage.app',
    measurementId: 'G-90JW58JEWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC60fyODiy8m75kwZvjRVocyIu_q0n6U74',
    appId: '1:1064041710776:android:b8b4666226b0f8b9b3e04d',
    messagingSenderId: '1064041710776',
    projectId: 'carnava-15594',
    storageBucket: 'carnava-15594.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQwoPVZIO6C694w8dxtIi3SmufzMPDPCI',
    appId: '1:1064041710776:ios:28d202276f5dee2bb3e04d',
    messagingSenderId: '1064041710776',
    projectId: 'carnava-15594',
    storageBucket: 'carnava-15594.firebasestorage.app',
    iosBundleId: 'com.example.carnavaAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQwoPVZIO6C694w8dxtIi3SmufzMPDPCI',
    appId: '1:1064041710776:ios:28d202276f5dee2bb3e04d',
    messagingSenderId: '1064041710776',
    projectId: 'carnava-15594',
    storageBucket: 'carnava-15594.firebasestorage.app',
    iosBundleId: 'com.example.carnavaAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb_qM0YRN5iFesfOXrAPQzcYUdRzJhn0g',
    appId: '1:1064041710776:web:3bbae2320ad78c12b3e04d',
    messagingSenderId: '1064041710776',
    projectId: 'carnava-15594',
    authDomain: 'carnava-15594.firebaseapp.com',
    storageBucket: 'carnava-15594.firebasestorage.app',
    measurementId: 'G-5066Q1P6BH',
  );
}
